CompeticionBundle\Entity\Clasificacion:
    type: entity
    table: clasificaciones
    repositoryClass: CompeticionBundle\Repository\ClasificacionRepository
    indexes:
        idx_competicion:
            columns:
                - competicion_id
        idx_participante:
            columns:
                - participante_id
        idx_categoria:
            columns:
                - categoria_id
        idx_modalidad:
            columns:
                - modalidad_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        totalPuntos:
            type: integer
        totalOnces:
            type: integer
        totalDieces:
            type: integer
        menor:
            type: integer
    manyToOne:
        participante:
            targetEntity: CompeticionBundle\Entity\Participante
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                participante_id:
                    referencedColumnName: id
            orphanRemoval: false
        competicion:
            targetEntity: Competicion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                competicion_id:
                    referencedColumnName: id
            orphanRemoval: false
        modalidad:
            targetEntity: CataBundle\Entity\Modalidad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                modalidad_id:
                    referencedColumnName: id
            orphanRemoval: false
        categoria:
            targetEntity: CataBundle\Entity\Categoria
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria_id:
                    referencedColumnName: id
            orphanRemoval: false
    
    lifecycleCallbacks: {  }
