<?php

namespace CorreoBundle\Repository;

/**
 * DestinatarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinatarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryByCorreo($correo_id) {
        $em = $this->getEntityManager();
		$db = $em->getConnection();
        $query = " select destinatarios.id as id "
                . ", personas.id as persona_id " 
                . " ,personas.email as eMail " 
                . " ,concat(personas.nombre,' ',personas.apellido1,' ',personas.apellido2) as nombre"
                ."  from destinatarios "
                ." inner join personas on personas.id = destinatarios.persona_id "
                . "where correo_id = :correo_id";
        $stmt = $db->prepare($query);
		$params = [":correo_id" => $correo_id];
		$stmt->execute($params);
		$po = $stmt->fetchAll();
		return $po;
    }
}
