ModelBundle\Entity\Activo:
    type: entity
    table: activos
    uniqueConstraints:
        idx_inventario:
            columns:
                - inventario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        inventario:
            type: integer
            nullable: true
            options:
                unsigned: false
        fcadquision:
            type: date
            nullable: true
        importeCompra:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: importe-compra
        importeAmortizado:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: importe-amortizado
    lifecycleCallbacks: {  }
