ModelBundle\Entity\Asiento:
    type: entity
    table: asientos
    indexes:
        idx_ejercicio:
            columns:
                - ejercicio_id
        idx_proyecto:
            columns:
                - proyecto_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numero:
            type: integer
            nullable: false
            options:
                unsigned: false
        fecha:
            type: date
            nullable: false
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        observaciones:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        importeDebe:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: importe_debe
        importeHaber:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: importe_haber
    manyToOne:
        ejercicio:
            targetEntity: Ejercicio
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ejercicio_id:
                    referencedColumnName: id
            orphanRemoval: false
        proyecto:
            targetEntity: Proyecto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                proyecto_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
