ModelBundle\Entity\Categoria:
    type: entity
    table: categorias
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codigo:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
        descripcion:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        edadDesde:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: edad_desde
        edadHasta:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: edad_hasta
    lifecycleCallbacks: {  }
