ModelBundle\Entity\Eventos:
    type: entity
    table: eventos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        tipoEvento:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tipo_evento
    lifecycleCallbacks: {  }
