ModelBundle\Entity\Imagenes:
    type: entity
    table: imagenes
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imagen:
            type: blob
            nullable: false
            length: 16777215
            options:
                fixed: false
    lifecycleCallbacks: {  }
