ModelBundle\Entity\OrigenIngresos:
    type: entity
    table: origen_ingresos
    indexes:
        idx_cuenta_mayor:
            columns:
                - cuenta_mayor_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        cuentaMayor:
            targetEntity: CuentasMayor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cuenta_mayor_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
