ModelBundle\Entity\UsuariosConexiones:
    type: entity
    table: usuarios_conexiones
    indexes:
        idx_usuario:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fcconexion:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        ip:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        dsconexion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        usuario:
            targetEntity: Usuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
