<?php

namespace CompeticionBundle\Repository;

/**
 * ClasificacionRondaRepository
 *
 * This class was generated by the Doctrine orm. Add your own custom
 * repository methods below.
 */
class ClasificacionRondaRepository extends \Doctrine\orm\EntityRepository
{
}
