ContabilidadBundle\Entity\CuentaMayor:
    type: entity
    table: cuentas_mayor
    repositoryClass: ContabilidadBundle\Repository\CuentaMayorRepository
    indexes:
        idx_grupo_cuentas:
            columns:
                - grupo_cuentas_id
        idx_tipo_cuenta:
            columns:
                - tipo_cuenta_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codigo:
            type: string
            nullable: true
            length: 9
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        grupoCuenta:
            targetEntity: GrupoCuenta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                grupo_cuentas_id:
                    referencedColumnName: id
            orphanRemoval: false
        tipoCuenta:
            targetEntity: TipoCuenta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_cuenta_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
