ContabilidadBundle\Entity\TipoIva:
    type: entity
    table: tipos_iva
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        tipo:
            type: float
            nullable: true
            precision: 10
            scale: 0
        porcentaje:
            type: float
            nullable: true
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
