<?php

namespace ContabilidadBundle\Repository;

/**
 * AsientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApunteRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryByAsiento($asiento_id) {
        $em = $this->getEntityManager();
		$db = $em->getConnection();
		
        $query = " select apuntes.id as id "
                ." ,apuntes.numero as numero"
                ." ,apuntes.descripcion as descripcion "
                ." ,apuntes.cuenta_debe_id as cuenta_debe_id "
                ." ,cuentas_mayor_debe.descripcion as cuentaDebe"
                ." ,apuntes.importe_debe as importeDebe "
                ." ,cuentas_mayor_haber.descripcion as cuentaHaber"
                ." ,apuntes.importe_haber as importeHaber "
                ." ,asientos.id as asiento_id "
                ." from apuntes "
                ." inner join asientos on asientos.id = apuntes.asiento_id "
                ." left join cuentas_mayor as cuentas_mayor_debe on apuntes.cuenta_debe_id = cuentas_mayor_debe.id "
                ." left join cuentas_mayor as cuentas_mayor_haber on apuntes.cuenta_haber_id = cuentas_mayor_haber.id "
                ." where apuntes.asiento_id = :asiento_id"
                ." order by asientos.numero "
                ;
        $stmt = $db->prepare($query);
		$params = array(":asiento_id" => $asiento_id);
		$stmt->execute($params);
		$po = $stmt->fetchAll();
		
		return $po;
		
    }
}
