<?php

namespace ContabilidadBundle\Repository;

/**
 * AsientoIngresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsientoIngresoRepository extends \Doctrine\ORM\EntityRepository
{
}
