<?php

namespace ContabilidadBundle\Repository;

/**
 * AsientoTraspasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsientoTraspasoRepository extends \Doctrine\ORM\EntityRepository
{
}
