<?php

namespace ContabilidadBundle\Repository;

/**
 * AsientoFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsientoFacturaRepository extends \Doctrine\ORM\EntityRepository
{
}
