<?php

namespace ContabilidadBundle\Repository;
/**
 * AsientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaMayorRepository extends \Doctrine\ORM\EntityRepository
{
    
}
