<?php

namespace ContabilidadBundle\Repository;

/**
 * EjercicioActualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EjercicioActualRepository extends \Doctrine\ORM\EntityRepository
{
}
