<?php

namespace ContabilidadBundle\Repository;

/**
 * EstadoEjercicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoEjercicioRepository extends \Doctrine\ORM\EntityRepository
{
}
