<?php

namespace ModelBundle\Repository;

/**
 * FicheroRepository
 *
 * This class was generated by the Doctrine orm. Add your own custom
 * repository methods below.
 */
class FicheroRepository extends \Doctrine\orm\EntityRepository
{
}
